package de.passwordvault.model.storage.app;


/**
 * Interface requires methods that allow the conversion to / from a string-representation that can
 * be stored.
 *
 * @author  Christian-2003
 * @version 3.3.0
 */
public interface Storable {

    /**
     * Method converts this instance into a string-representation which can be used for persistent
     * storage. The generated string can later be parsed into a storable through
     * {@link #fromStorable(String)}.
     *
     * @return  String-representation of this instance.
     */
    String toStorable();

    /**
     * Method creates the instance from it's passed string-representation. The passed string - which
     * is a storable's string-representation - must be generated by {@link #toStorable()} beforehand.
     *
     * @param s                     String-representation from which to create the instance.
     * @throws StorageException     The passed string could not be converted into an instance.
     * @throws NullPointerException The passed string is {@code null}.
     */
    void fromStorable(String s) throws StorageException, NullPointerException;

}
