package de.christian2003.core.security.application.services

import org.junit.Assert
import org.junit.Test
import java.util.Random


//Notice: These tests are generated by AI
class RecoveryCodeEncoderServiceUnitTest {

    private val encoder = RecoveryCodeEncoderService()

    private val random = Random()


    @Test
    fun `encode then decode returns original bytes`() {
        //With:
        val input = byteArrayOf(0x00, 0x01, 0x02, 0x10, 0x20, 0x7F, 0x55, 0x66, 0x77, 0x7E, 0x7D)


        //When:
        val encoded = encoder.encode(input)
        val decoded = encoder.decode(encoded)


        //Then:
        Assert.assertArrayEquals(input, decoded)
    }


    @Test
    fun `random round trip`() {
        //With:
        val length = random.nextInt(64) + 1
        val input = ByteArray(length)
        random.nextBytes(input)


        //When:
        val encoded = encoder.encode(input)
        val decoded = encoder.decode(encoded)


        //Then:
        Assert.assertArrayEquals(input, decoded)
    }


    @Test
    fun `empty array`() {
        //With:
        val input = ByteArray(0)


        //When:
        val encoded = encoder.encode(input)
        val decoded = encoder.decode(encoded)


        //Then:
        Assert.assertArrayEquals(input, decoded)
    }


    @Test
    fun `single byte`() {
        //With:
        val input = byteArrayOf(0x7F)


        //When:
        val encoded = encoder.encode(input)
        val decoded = encoder.decode(encoded)


        //Then:
        Assert.assertArrayEquals(input, decoded)
    }


    @Test
    fun `invalid character throws exception`() {
        //With:
        val invalid = charArrayOf('A', 'B', '*', 'C')


        //When:
        Assert.assertThrows(IllegalArgumentException::class.java) {
            encoder.decode(invalid)
        }
    }


    @Test
    fun `tolerant characters decode correctly`() {
        //With:
        val original = byteArrayOf(0x12, 0x34, 0x56, 0x78)


        //When:
        val encoded = encoder.encode(original)

        // Replace valid chars with ambiguous ones
        val modified = encoded.map {
            when (it) {
                '0' -> 'O'
                '1' -> 'I'
                else -> it
            }
        }.toCharArray()

        val decoded = encoder.decode(modified)


        //Then:
        Assert.assertArrayEquals(original, decoded)
    }

}
